# fly.toml app configuration file generated for delicate-paper-3097 on 2023-06-12T23:55:17+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "delicate-paper-3097"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
